stages:
  - validate
#  - deploy_to_test
#  - deploy_to_prod
  - deploy_to_test
  - test
  - verify_deploy_to_test
#  - verify_deploy_to_prod

lint:
  stage: validate
  #image: kecorbin/ansible:devel
  image: ansible-runner:0.3
  script:
#    - ansible-playbook --syntax-check -i inventory/dev.yaml site.yaml
#    - ansible-playbook --syntax-check -i inventory/test.yaml site.yaml
#    - ansible-playbook --syntax-check -i inventory/prod.yaml site.yaml
    - ansible-playbook --syntax-check -i inventory/cml-sandbox.yaml site_addLoopback100.yaml

deploy_to_test:
  #image: kecorbin/ansible:devel
  image: ansible-runner:0.3
  stage: deploy_to_test
  script:
    - echo "Deploy to cml env"
    - ansible-playbook -i inventory/cml-sandbox.yaml site_addLoopback100.yaml
  environment:
    name: test
  only:
    - test

validate_test_environment:
  image: ciscotestautomation/pyats:latest-robot
  stage: verify_deploy_to_test
  environment:
    name: test
  only:
    - test
  script:
    - pwd
    - cd tests
    # important: need to add our current directory to PYTHONPATH
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - robot --noncritical noncritical --variable testbed:./cml_testbed.yml cml_validation_tasks.robot

  artifacts:
      name: "pyats_robot_logs_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
      when: always
      paths:
        - ./tests/log.html
        - ./tests/report.html
        - ./tests/output.xml

